### ISSUE TITLE
Implement Firebase Authentication for Login and Connect to Backend

### ISSUE THREAD

**Issue by zleypner** [safetrustcr/Frontend#187]
# Implement Hasura Authentication with Docker Backend
---
## Issue Summary
We need to implement Hasura Authentication for the login system in our frontend application and establish proper communication with our Hasura GraphQL backend running in Docker.

## Type of Issue
- [x] Feature Request
- [ ] Bug
- [ ] Documentation
- [ ] Performance
- [ ] Security
- [ ] Other (please specify)

## Current Behavior
Currently, the application lacks a robust authentication system. Users cannot log in using secure authentication services, and there's no proper integration between the frontend authentication and our Hasura GraphQL backend.

## Expected Behavior
Users should be able to log in to the application using Hasura Authentication. The frontend should securely communicate with our Hasura GraphQL backend, passing JWT tokens for validation and user session management.

## Reproduction Steps
1. Navigate to the login page
2. Attempt to log in
3. No authentication is available
4. No proper JWT token is passed to the backend

## Environment Details
- Project Version: v0.1.0
- Operating System: All platforms
- Browser/Runtime: All modern browsers
- Additional Tools: Docker, Hasura GraphQL Engine

#### Frontend Requirements:
1. Install necessary dependencies: `npm install graphql graphql-request jwt-decode`
2. Set up authentication configuration in the project
3. Implement the following authentication methods:
   - Email/Password
   - JWT token management
4. Create authentication context/store using Zustand (already a dependency)
5. Add token persistence for session management
6. Implement protected routes that require authentication
7. Pass JWT tokens to Hasura GraphQL API calls

#### Backend Integration:
1. Configure Hasura JWT authentication in Docker
2. Set up proper permissions in Hasura for authenticated users
3. Create custom Docker service for authentication logic
4. Set up proper error handling for authentication failures
5. Configure user tables and permissions in Hasura

#### Hasura JWT Configuration (Docker):
```yaml
# Example docker-compose.yml snippet
services:
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"your-secret-key-here", "claims_namespace":"https://hasura.io/jwt/claims"}'
      HASURA_GRAPHQL_ADMIN_SECRET: youradminsecretkey
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    depends_on:
      - postgres
  
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: your-secret-key-here
      HASURA_ADMIN_SECRET: youradminsecretkey
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
    depends_on:
      - hasura
```

#### Authentication Service (Node.js):
```javascript
// Example auth-service/index.js
const express = require('express');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcrypt');
const { request, gql } = require('graphql-request');

const app = express();
app.use(express.json());

// Login endpoint
app.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    
    // Query user from Hasura
    const query = gql`
      query GetUser($email: String!) {
        users(where: {email: {_eq: $email}}) {
          id
          password
        }
      }
    `;
    
    const response = await request(
      process.env.HASURA_ENDPOINT,
      query,
      { email },
      { 'x-hasura-admin-secret': process.env.HASURA_ADMIN_SECRET }
    );
    
    const user = response.users[0];
    if (!user || !bcrypt.compareSync(password, user.password)) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }
    
    // Generate JWT with Hasura claims
    const token = jwt.sign({
      'https://hasura.io/jwt/claims': {
        'x-hasura-allowed-roles': ['user'],
        'x-hasura-default-role': 'user',
        'x-hasura-user-id': user.id.toString()
      }
    }, process.env.JWT_SECRET);
    
    res.json({ token });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.listen(3001, () => {
  console.log('Auth service running on port 3001');
});
```

#### Frontend Authentication Store:
```typescript
// Example authStore.ts
import create from 'zustand';
import { persist } from 'zustand/middleware';
import jwtDecode from 'jwt-decode';

interface AuthState {
  token: string | null;
  user: any | null;
  isLoading: boolean;
  error: string | null;
  login: (email: string, password: string) => Promise<void>;
  logout: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      token: null,
      user: null,
      isLoading: false,
      error: null,
      
      login: async (email, password) => {
        try {
          set({ isLoading: true, error: null });
          
          const response = await fetch('http://localhost:3001/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email, password })
          });
          
          if (!response.ok) {
            const error = await response.json();
            throw new Error(error.error || 'Login failed');
          }
          
          const { token } = await response.json();
          const decoded = jwtDecode(token);
          
          set({
            token,
            user: decoded,
            isLoading: false
          });
        } catch (error) {
          set({ isLoading: false, error: error.message });
        }
      },
      
      logout: () => {
        set({ token: null, user: null });
      }
    }),
    {
      name: 'auth-storage'
    }
  )
);
```

### Required Updates
1. Backend:
   - Configure Hasura with JWT authentication in Docker
   - Create authentication service container
   - Set up user tables and permissions in Hasura
   - Configure environment variables
2. Frontend:
   - Add GraphQL and JWT dependencies
   - Create authentication store with Zustand
   - Update API utility to include JWT authentication headers
   - Implement login/register forms and protected routes

### Make sure to follow the Git Guidelines for Atomic Commits and read [Contributing Guide](https://github.com/safetrustcr/Frontend/issues/34)
The Pull request needs to have the format mentioned below in the Git Guideline
- [Contributing Guide](https://github.com/safetrustcr/Frontend/issues/34)
- [[Git Guidelines](https://github.com/safetrustcr/Frontend/issues/35)](https://github.com/safetrustcr/Frontend/issues/35)
